package ppp.model;

import javax.swing.*;

/**
 * Project: Maero
 * Title: Users
 * Description: This class will work as a Superclass that contains general attributes.
 * Also it will be used to inherit all the properties and methods to three subclasses (Customer, Receptionist, Admin).
 * Attribute of userID will be generated by program when admin creating user account and used to differentiate user types.
 * Version 1.0
 * Created by Dylan on 27/09/2014.
 */

public class User {

    private String firstName;
    private String lastName;
    private String password;
    private String eamil;
    private String address;
    private String phoneNum;
    private String usertypeStr;

    public String getFirstName()
    {
        return firstName;
    }

    public void setFirstName(String firstName)
    {
        this.firstName = firstName;
    }

    public String getLastName()
    {
        return lastName;
    }

    public void setLastName(String lastName)
    {
        this.lastName = lastName;
    }

    public String getPassword()
    {
        return password;
    }

    public void setPassword(String password)
    {
        this.password = password;
    }

    public String getEamil()
    {
        return eamil;
    }

    public void setEamil(String eamil)
    {
        this.eamil = eamil;
    }

    public String getAddress()
    {
        return address;
    }

    public void setAddress(String address)
    {
        this.address = address;
    }

    public String getPhoneNum()
    {
        return phoneNum;
    }

    public void setPhoneNum(String phoneNum)
    {
        this.phoneNum = phoneNum;
    }

    public String getUsertypeStr()
    {
        return usertypeStr;
    }

    public void setUsertypeStr(String usertypeStr)
    {
        this.usertypeStr = usertypeStr;
    }

    public User(String firstName, String lastName, String password, String eamil, String address, String phoneNum, String usertypeStr)
    {
        this.firstName = firstName;
        this.lastName = lastName;
        this.password = password;
        this.eamil = eamil;
        this.address = address;
        this.phoneNum = phoneNum;
        this.usertypeStr = usertypeStr;


    }

    //    public void displayBookDetails() {
//        //this will print title/author of all books
//        //statement can be refined and expanded
//        System.out.println("Creating statement...");
//        stmt = conn.createStatement();
//
//        String sql = "SELECT * FROM books";
//        ResultSet rs = stmt.executeQuery(sql);
//        //STEP 5: Extract data from result set
//        while(rs.next()){
//            //Retrieve by column name
//            String bookTitle = rs.getString("TITLE");
//            String bookAuthor = rs.getString("AUTHOR");
//
//            //Display values
//            System.out.println("THESE ARE THE BOOKS WE HAVE: " + bookTitle + "-" + bookAuthor);
//        }
//        rs.close();
//    }

    public static void userLogin(){

        //these variables will be taken from the db
        String dbUserName = "test";
        String dbPassword = "123";

        //GUI enter username & password
        JOptionPane.showMessageDialog(null, "Library login prompt");
        String userInputName = JOptionPane.showInputDialog("Enter user name");
        String userInputPass = JOptionPane.showInputDialog("Enter password");


        //authentication - compares users input to database
        if (userInputName.equals(dbUserName) && userInputPass.equals(dbPassword)) {
            JOptionPane.showMessageDialog(null,
                    "Login successful.");
        } else {
            JOptionPane.showMessageDialog(null,
                    "Incorrect username or password.",
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
        }
    }


}
