DROP DATABASE IF EXISTS maero;

CREATE DATABASE maero;

DROP TABLE IF EXISTS SUBJECTS;
DROP TABLE IF EXISTS GENRES;
DROP TABLE IF EXISTS USER_TYPES;
DROP TABLE IF EXISTS BOOKS;
DROP TABLE IF EXISTS USERS;
DROP TABLE IF EXISTS BORROWED_BOOKS;

CREATE TABLE SUBJECTS(
SUBJECT_ID INTEGER PRIMARY KEY AUTO_INCREMENT,
SUBJECT_NAME VARCHAR(30) NOT NULL
)ENGINE=INNODB;

CREATE TABLE GENRES(
GENRE_ID INTEGER PRIMARY KEY AUTO_INCREMENT,
GENRE_NAME VARCHAR(30) NOT NULL
)ENGINE=INNODB;

CREATE TABLE USER_TYPES(
USER_TYPE_ID INTEGER PRIMARY KEY AUTO_INCREMENT,
USER_TYPE_NAME VARCHAR(30) NOT NULL
)ENGINE=INNODB;

CREATE TABLE BOOKS (
BOOK_ID INTEGER PRIMARY KEY AUTO_INCREMENT,
TITLE VARCHAR(30) NOT NULL,
AUTHOR VARCHAR(30) NOT NULL,
ISBN VARCHAR(20) NOT NULL,
SHOP_NAME VARCHAR(30) NOT NULL,
PRICES NUMERIC(4,2) NOT NULL,
PUBLISHNATION VARCHAR(50) NOT NULL,
SUBJECT_ID INTEGER,
GENRE_ID INTEGER,

FOREIGN KEY (SUBJECT_ID) REFERENCES SUBJECTS(SUBJECT_ID),
FOREIGN KEY (GENRE_ID) REFERENCES GENRES(GENRE_ID)
)ENGINE=INNODB;

CREATE TABLE USERS(
USER_ID INTEGER PRIMARY KEY AUTO_INCREMENT,
USER_NAME VARCHAR(30) NOT NULL,
ENTRY_TIME DATETIME NOT NULL,
EXIT_TIME DATETIME,
EMAIL VARCHAR(200) NOT NULL,
PASSWORD VARCHAR(20) NOT NULL,
ADDRESS VARCHAR(300),
PHONE_NUMBER VARCHAR(30),
USER_TYPE_ID INTEGER,
TOTAL_FINE_AMOUNT NUMERIC(4,2),

FOREIGN KEY (USER_TYPE_ID) REFERENCES USER_TYPES(USER_TYPE_ID)
)ENGINE=INNODB;

CREATE TABLE BORROWED_BOOKS(
BORROWED_BOOK_ID INTEGER PRIMARY KEY AUTO_INCREMENT,
FINE NUMERIC(4,2),
BORROWED_TIME DATETIME NOT NULL,
RERURNED_TIME DATETIME,
BOOK_ID INTEGER,
USER_ID INTEGER,

FOREIGN KEY (BOOK_ID) REFERENCES BOOKS(BOOK_ID),
FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID)
)ENGINE=INNODB;